apiVersion: v1
kind: Service
metadata:
  labels:
    name: api
  # le nom de service
  name: api 
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
  selector:
    app: deno-app


